name: dcci_good_receipt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_launcher_icons:
  image_path: "assets/images/dcci.png"
  android: true
  ios: true